name: Develop Branch CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.103

    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
      
    - name: Run dotnet format
      run: dotnet format --verbosity diagnostic
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build with analyzers
      run: dotnet build --no-restore /p:EnforceCodeStyleInBuild=true /p:AnalysisMode=All
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Verify migrations
      run: |
        dotnet tool install --global dotnet-ef
        dotnet ef migrations script --idempotent --output=migrations-script.sql --project Project.Infrastructure --startup-project Project.API
      continue-on-error: true  

