name: Develop Branch CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
      
    - name: Run dotnet format check
      run: dotnet format --verify-no-changes
      continue-on-error: true

    - name: Run dotnet format fix
      run: dotnet format --fix all --check --verbosity diagnostic --include /src/Project.API/Project.API.csproj --include /src/Project.Infrastructure/Project.Infrastructure.csproj --include /src/Project.Domain/Project.Domain.csproj --include /src/Project.Application/Project.Application.csproj --include /src/Project.Tests/Project.Tests.csproj --include /src/Project.Tests.Integration/Project.Tests.Integration.csproj --include /src/Project.Tests.Unit/Project.Tests.Unit.csproj

    - name: Inspect Code Format Changes
      id: verify_diff
      run: git diff --quiet . || echo "changed=true" >> $
      
    - name: Commit Changes
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        git config --global user.name 'MathNumber'
        git config --global user.email 'ducpd82@gmail.com'
        git config --global core.autocrlf false
        git pull
        git commit -am "CI: autoformat"
        git push

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build with analyzers
      run: dotnet build --no-restore /p:EnforceCodeStyleInBuild=true /p:AnalysisMode=All
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Verify migrations
      run: |
        dotnet tool install --global dotnet-ef
        dotnet ef migrations script --idempotent --output=migrations-script.sql --project Project.Infrastructure --startup-project Project.API
      continue-on-error: true  

