name: Develop Branch CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
  
    steps:
    - uses: actions/checkout@v3

    - name: Checkout as Administrator
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Setup CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp
        build-mode: none
    
    - name: Build with analyzers
      run: dotnet build --no-restore /p:EnforceCodeStyleInBuild=true /p:AnalysisMode=All

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
      
    - name: Run dotnet format check
      run: dotnet format --verify-no-changes
      continue-on-error: true

    - name: Run dotnet format fix
      run: dotnet format

    - name: Inspect Code Format Changes
      id: verify_diff
      run: git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      
    - name: Commit Changes
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        git config --global user.name 'Duc Nguyen'
        git config --global user.email 'ducpd82@gmail.com'
        git config --global core.autocrlf false
        git pull
        git commit -am "CI: autoformat"
        git push

    - name: Security Scan
      uses: github/codeql-action/analyze@v3

    - name: Verify migrations
      run: |
        dotnet tool install --global dotnet-ef
        dotnet ef migrations script --idempotent --output=migrations-script.sql --project Project.Infrastructure --startup-project Project.API
      continue-on-error: true  

