name: Auto Format

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout as Administrator
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format
      - name: Run dotnet format check
        run: dotnet format --verify-no-changes
        continue-on-error: true
      - name: Run dotnet format fix
        run: dotnet format
      - name: Inspect Code Format Changes
        id: verify_diff
        run: git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit Changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'Duc Nguyen'
          git config --global user.email 'ducpd82@gmail.com'
          git config --global core.autocrlf false
          git pull
          git commit -am "CI: autoformat"
          git push
